language: php

php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

sudo: false

env:
  - WP_VERSION=master WP_MULTISITE=0

before_script:
  # Install wordpress
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR

  # TODO: Install woocommerce

  # Install plugin
  - plugin_name=$(basename $(pwd))
  - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_name
  - cd $WP_DEVELOP_DIR
  - mv $plugin_name $plugin_dir
  - echo $WP_DEVELOP_DIR
  - ls $WP_DEVELOP_DIR
  - ls $plugin_dir

script:
  # Check syntax errors
  - cd $plugin_dir && find . \( -name '*.php' \) -exec php -lf {} \;
